name: Django CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: test_db
          MYSQL_USER: test_user
          MYSQL_PASSWORD: test_pass
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    env:
      DJANGO_SECRET_KEY: testsecretkey
      DB_NAME: test_db
      DB_USER: test_user
      DB_PASSWORD: test_pass
      DB_HOST: 127.0.0.1
      DB_PORT: 3306

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r messaging_app/requirements.txt
          pip install flake8 coverage pytest

      - name: Wait for MySQL to be ready
        run: sleep 20

      - name: Run flake8 Linting
        run: |
          echo "Running flake8..."
          flake8 messaging_app/
        # This step fails the build on any linting error

      - name: Run migrations
        run: |
          python manage.py migrate
        working-directory: ./messaging_app

      - name: Run Tests with Coverage
        run: |
          coverage run -m pytest
          coverage report
          coverage html
        working-directory: ./messaging_app

      - name: Upload Coverage Report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-html
          path: messaging_app/htmlcov/
